### ISSUE TITLE
new changes

### ISSUE THREAD

**Issue by gaureshpai** [jtuluve/AJIMS#37]
### Backend (assigned to: @jtuluve @VikramNaik26  )

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------
### **1.  Research:**

i. Publication : all req
1. [x] Sorted according to the Year - Newest first
2. [x] Add National/ International/ Institutional - Select option  ( heading to be known)(category - temporary heading)
3. [x] Post held while published - text box
------------------------------------------------------------------------------------------------------------------
ii. Grants: all req
1. [x] Start Year - date
2. [x] End Year - date (not req)
3. [x] Attachment - Utilization Certificate (not req)
4. [x] Current heading of the Attachment - Upload Proposal
5. [x] Work Published - Yes/ No
------------------------------------------------------------------------------------------------------------------
iii. Books: all req
1. [x] Add an Attachment Option
2. [x] Year of Publication - date
3. [x] Attachment - Certificate/ Acknowledgement
4. [x] Title of the book/Chapter - text
5. [x] Book details - text
------------------------------------------------------------------------------------------------------------------
iv. Guidance: all req
1. [x] Provide provision for addition of multiple student details
2. [x] Add attachment options in front of the student detail
3. [x] Add project start date and end date option in front of student detail
4. [x] Add published the work (Yes/No) option
5. [x] Remove Number
6. [x] Title - text
7. [x] Student name/Details - text
8. [x] Year start and end  - text
9. [x] Attachment 3 -> 1 - synopsis, 2 - thesis, 3 - project report
10. [x] Funded - Yes/No
11. [x] if Yes: Funding Agency Name - text 
12. [x] Grant Name - text
13. [x] Amount - number
14. [x] Work Published - yes/no
------------------------------------------------------------------------------------------------------------------
v. Conference: all req
1. [x] Add Conference Name and Detail Section
2. [x] Add Attachment Option
3. [x] Remove number
4. [x] In Category add -  Zonal/State/National/International 
5. [x] Year - date
6. [x] Poster/Oral/Attending - type
7. [x] Conference Name - text
8. [x] Place of Conference - text
9. [x] Awards Received - yes/no
10. [x] If Yes: Description - text

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

### **2. Academics:**

1. [x] Provide Option for Deleting the Uploaded file
2. [x] Upload for everything - attachment 
3. [x] Sort everything according to the Year - newest being first
4. [x] Add ->  add/edit/delete button
5. [x] Academics print -> scroll bar remove, watermark in the background

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

### **3.  Professional:**

1. [x] Conference/Workshop/CME:
2. [x] - Provide provision to select Conference/Workshop/CME
3. [x] - Provide a Title Section
4. [x] - Selection for Institutional/District/State/National/International
5. [x] - In Designation tab Add Resource Person as one more Option
6. [x] Provide Attachment Option under each Form
7. [x] Provide Option for Deleting the Uploaded file

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

### **4.  Admin Page:**
 
1. [x] 5 page format as the print given
2. [x] Segregation of faculties based on department
3. [x] Search option
4. [x] Individual faculty details in a page format
5. [x] Individual faculty details segregated on yearly basis

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

### **5. Profile page:**

1. [x] KMC reg no - number -> text
2. [x] Add - Age - number ( after dob)
3. [x] Appointment Order - Attachment ( after Designation) ( add/edit/delete)
4. [x] Category - removed
5. [x] Educational Qualification - add/edit/delete
6. [x] Main page - admin page view - first page only

------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------

**Comment by gaureshpai** [comment]
We starting these after exams? i.e April 19th??

**Comment by gaureshpai** [comment]
@jtuluve Conferences delete not working!

**Comment by jtuluve** [comment]
Nice😭

**Comment by gaureshpai** [comment]
Admin page
1
![IMG_20240423_022817](https://github.com/jtuluve/AJIMS/assets/107191770/f0bdd62b-b7ae-49f6-92fe-d360508498c7)
2
![IMG_20240423_022827](https://github.com/jtuluve/AJIMS/assets/107191770/e522b3e4-28bf-41f4-8b7d-96ccca803532)
3
![IMG_20240423_022835](https://github.com/jtuluve/AJIMS/assets/107191770/9db4d266-c193-4984-accf-b12767755a1e)
4
![IMG_20240423_022846](https://github.com/jtuluve/AJIMS/assets/107191770/789290de-06f5-4358-8300-e3eb881138f7)

**Comment by gaureshpai** [comment]
Issues and enhancements
1
![IMG_20240422_154049](https://github.com/jtuluve/AJIMS/assets/107191770/fe7253b6-831a-4086-91a5-6e158b65853f)
2
![IMG_20240422_154053](https://github.com/jtuluve/AJIMS/assets/107191770/1bd62a0e-3a2c-4d19-9d71-c802d312e4fd)

**Comment by gaureshpai** [comment]
Front end part 1 done!

**Comment by gaureshpai** [comment]
Frontend done
